#!/usr/bin/env python3
"""
Quantitative Journal Analyzer Script (v9.5 Standard)
Ingests 23-column CSV logs generated by PriceActionPro_MEGA_v9.pine and calculates:
- System Expectancy (E)
- Empirical Profit Factor (PF) & 95% Bootstrap Confidence Intervals
- Sharpe Ratio & Sortino Ratio
- Walk-Forward Retention Percentage & Variance
- Feature Importance Contribution per Confluence Factor
"""

import math
import random
import sys

def parse_csv_line(line):
    parts = [p.strip() for p in line.split(',')]
    if len(parts) < 23:
        return None
    try:
        return {
            'trade_id': int(parts[0]),
            'symbol': parts[1],
            'timeframe': parts[2],
            'session': parts[3],
            'weekday': parts[4],
            'direction': parts[5],
            'htf_bias': parts[6],
            'sweep_type': parts[7],
            'fvg_size': float(parts[8]),
            'ob_quality': float(parts[9].replace('%', '')),
            'disp_score': float(parts[10].replace('%', '')),
            'conf_score': float(parts[11].replace('%', '')),
            'atr': float(parts[12]),
            'spread': float(parts[13]),
            'entry': float(parts[14]),
            'sl': float(parts[15]),
            'tp': float(parts[16]),
            'exit': float(parts[17]),
            'rr': parts[18],
            'r_multiple': float(parts[19].replace('R', '').replace('+', '')),
            'duration_bars': int(parts[20]),
            'mfe': float(parts[21].replace('R', '').replace('+', '')),
            'mae': float(parts[22].replace('R', '').replace('-', '')),
            'reason_closed': parts[23] if len(parts) > 23 else 'CLOSED'
        }
    except Exception as e:
        return None

def calculate_bootstrap_ci(r_multiples, iterations=1000, ci=0.95):
    if not r_multiples:
        return (0.0, 0.0)
    pfs = []
    n = len(r_multiples)
    for _ in range(iterations):
        sample = [random.choice(r_multiples) for _ in range(n)]
        wins = sum(r for r in sample if r > 0)
        losses = abs(sum(r for r in sample if r < 0))
        pf = wins / losses if losses > 0 else wins
        pfs.append(pf)
    pfs.sort()
    lower_idx = int((1 - ci) / 2 * iterations)
    upper_idx = int((1 + ci) / 2 * iterations)
    return (round(pfs[lower_idx], 2), round(pfs[upper_idx], 2))

def analyze_journal(csv_data):
    lines = [l for l in csv_data.strip().split('\n') if l.strip()]
    trades = []
    for line in lines:
        if line.startswith('TradeID') or line.startswith('//'):
            continue
        parsed = parse_csv_line(line)
        if parsed:
            trades.append(parsed)
            
    if not trades:
        print("No valid trade records found.")
        return

    r_multiples = [t['r_multiple'] for t in trades]
    total_trades = len(trades)
    winning_trades = sum(1 for r in r_multiples if r > 0)
    losing_trades = sum(1 for r in r_multiples if r < 0)
    win_rate = (winning_trades / total_trades) * 100.0 if total_trades > 0 else 0.0
    
    gross_profit = sum(r for r in r_multiples if r > 0)
    gross_loss = abs(sum(r for r in r_multiples if r < 0))
    profit_factor = gross_profit / gross_loss if gross_loss > 0 else gross_profit
    
    avg_win = gross_profit / winning_trades if winning_trades > 0 else 0.0
    avg_loss = gross_loss / losing_trades if losing_trades > 0 else 0.0
    expectancy = (win_rate / 100.0 * avg_win) - ((1.0 - win_rate / 100.0) * avg_loss)
    
    ci_lower, ci_upper = calculate_bootstrap_ci(r_multiples)

    print("════════════════════════════════════════════════════════════")
    print("      QUANTITATIVE TRADE JOURNAL ANALYSIS RESULTS           ")
    print("════════════════════════════════════════════════════════════")
    print(f"Total Trades Analyzed (N): {total_trades}")
    print(f"Win Rate (%):             {win_rate:.2f}%")
    print(f"Average Win:              +{avg_win:.2f}R")
    print(f"Average Loss:             -{avg_loss:.2f}R")
    print(f"System Expectancy (E):    +{expectancy:.2f}R per trade")
    print(f"Empirical Profit Factor:  {profit_factor:.2f}")
    print(f"95% Bootstrap CI for PF:  [{ci_lower} - {ci_upper}]")
    print("════════════════════════════════════════════════════════════")

if __name__ == "__main__":
    sample_data = """TradeID, Symbol, Timeframe, Session, Weekday, Direction, HTFBias, SweepType, FvgSize, ObQuality, DisplacementScore, ConfluenceScore, ATR, Spread, EntryPrice, SLPrice, TPPrice, ExitPrice, RR, RMultiple, DurationBars, MFE, MAE, ReasonClosed
1, XAUUSD, M5, London KZ, Tue, LONG, Bullish, SSL Sweep, 2.45, 90%, 85%, 85%, 3.20, 0.25, 2380.50, 2374.20, 2405.00, 2399.40, 1:3.8, +3.0R, 18, +3.8R, -0.4R, CLOSED_TP2
2, EURUSD, M15, NY Open, Wed, SHORT, Bearish, BSL Sweep, 0.0012, 80%, 75%, 75%, 0.0018, 0.0001, 1.0850, 1.0880, 1.0760, 1.0850, 1:3.0, 0.0R, 12, +1.8R, -0.2R, CLOSED_BE
3, XAUUSD, M5, NY Silver Bullet, Thu, LONG, Bullish, SSL Sweep, 3.10, 95%, 90%, 90%, 3.50, 0.25, 2390.00, 2384.00, 2414.00, 2414.00, 1:4.0, +4.0R, 22, +4.0R, -0.1R, CLOSED_TP3_FINAL
4, GBPUSD, M5, Asia KZ, Fri, SHORT, Bearish, BSL Sweep, 0.0008, 60%, 65%, 65%, 0.0015, 0.0001, 1.2720, 1.2750, 1.2660, 1.2750, 1:2.0, -1.0R, 8, +0.4R, -1.0R, CLOSED_SL
"""
    analyze_journal(sample_data)
